name: A workflow for my file
on: push
jobs:
  build:
    name: docker
    runs-on: ubuntu-latest
    container: 
      image: lamastex/dockerdev:spark3x
      volumes: 
        - /github/workspace
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
      - run: pwd
      
